---
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [pre-commit]
default_language_version:
  python: python3.11

repos:
  # misc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [css, javascript, html, yaml, json]
  - repo: https://github.com/aanatoly/check-changelog
    rev: "0.4.1"
    hooks:
      - id: check-changelog
  # lua
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.1
    hooks:
      - id: stylua-github # or stylua-system / stylua-github
